name: Hello

on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          pip install dstack
      - name: Configure remote
        run: |
          dstack config aws --bucket dstack-142421590066-eu-west-1 --region eu-west-1
      - name: Initialize dstack
        run: |
          dstack init
      - name: Run remotely
        run: |
          dstack run hello --remote